In [10]:
import json
import numpy as np
import pandas as pd
import os
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt

In [2]:
df = np.load('../qm9_filtered.npy', allow_pickle = True)

In [3]:
df_X = []
df_y = []

for line in df:
    num = len(line['chiral_centers'])
    if num != 1:
        continue
    
    deg = line['rotation'][1]
    if deg > 0:
        sign = 1
    elif deg < 0:
        sign = 0
    else:
        continue
    
    df_X.append(line['xyz'].flatten())
    df_y.append(sign)
    
df_X = np.array(df_X)
df_y = np.array(df_y)

In [4]:
print(len(df_X), len(df_y))

22923 22923


In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_X, df_y, test_size = 0.2, random_state=120)

In [21]:
from xgboost import XGBClassifier

# Define the depths to search
max_depth_values = [5, 10, 20, 30]

# Initialize results list
results = []

# Iterate over different depths
for depth in max_depth_values:
    print(depth)
    clf = XGBClassifier(max_depth=depth, use_label_encoder=False, eval_metric='logloss', eta = 0.13)
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    y_train_pred = clf.predict(X_train)
    
    test_acc = accuracy_score(y_test, y_pred)
    test_f1 = f1_score(y_test, y_pred)
    
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    
#     results.append({"Depth": depth, "Test Accuracy": test_acc, "Test F1 Score": test_f1, "confusion_matrix": cm})

# # Convert results to DataFrame
# results_df = pd.DataFrame(results)

# results_df

5
[[1628  779]
 [ 884 1294]]
10
[[1738  669]
 [ 712 1466]]
20
[[1760  647]
 [ 656 1522]]
30
[[1742  665]
 [ 652 1526]]


In [15]:
# results_df.to_csv('XGB_PN_class_result.csv', index=False)